### ISSUE TITLE
출력폴더 또는 압축할폴더를 계속 변경할수 있게 해주세요

### ISSUE THREAD

**Issue by alcyone-code** [qn1213/FolderArchive#3]
현재 순서대로 출력폴더 압축할폴더 압축하기 하고나면 반드시 초기화 진행해야되는데

중간에 출력폴더나 압축할폴더를 변경 할 수 있게 해주시면 편할것 같습니다

**Comment by qn1213** [comment]
#5 처리하면서 완료오
