### ISSUE TITLE
출력폴더 선택, 폴더선택 고정할 수 없을까요?

### ISSUE THREAD

**Issue by lookyharu** [qn1213/FolderArchive#5]
자주 쓰는 프로그램인데 할 때마다 출력폴더 압축할폴더 일일히 계속 설정을 해야해서요 혹시 고정적으로 지정할 수 있는 방법은 없을까요

**Comment by qn1213** [comment]
엇 써주시는 분이 있었네요... 감사합니다!
다음주 중으로 고쳐서 업데이트 해놓겠습니다.

**Comment by qn1213** [comment]
지금 줜난 열심히 업데이트 중입니다.
조금만 기다려주세요오오

**Comment by lookyharu** [comment]
아휴 해주시기만 해도 감사합니다;;;

**Comment by qn1213** [comment]
업데이트 완료
릴리즈 확인해주세요!

**Comment by lookyharu** [comment]
감사합니다 작동 잘됩니다 인터페이스도 깔끔해져서 훨씬 좋네요
